### ISSUE TITLE
Unknown property 'ghidraInstallDir'?

### ISSUE THREAD

**Issue by biggestsonicfan** [hazzaaclark/gdiGhidra#1]
Greetings. My attempt  to build with 10.4 (I assume this will happen with other Ghidra versions) results in an error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/user/gits/gdiGhidra/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'gdiGhidra'.
> Could not get unknown property 'ghidraInstallDir' for root project 'gdiGhidra' of type org.gradle.api.Project.
```

I don't actually understand where `ghidraInstallDir` gets defined?

Manually applying the static location of `buildExtension.gradle` results in another error:

```
* Where:
Build file '/home/user/gits/gdiGhidra/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'gdiGhidra'.
> Could not find method BUILD_EXT() for arguments [build_cmd8vf08hun351koaf4lrb6v4$_run_closure1@4987aedd] on root project 'gdiGhidra' of type org.gradle.api.Project.
```

EDIT: I can't pretend that I know gradle, but changing `ghidraInstallDir` to `INSTALL_DIR` got my to the second error:
https://github.com/hazzaaclark/gdiGhidra/blob/855ce502c46135072901e192daabc2aa0ea203f1/build.gradle#L15

EDIT2: changing

https://github.com/hazzaaclark/gdiGhidra/blob/855ce502c46135072901e192daabc2aa0ea203f1/build.gradle#L22

to `def BUILD_EXT()` fixed the second error with a few notes:
- I am unsure how the instructions got the way they are, but `gradlew` appears to be a wrapper. The extension is build with just the `gradle` command.
- The output folder is `/dist` and not `/res` as stated in the readme.
- The resulting zip placed in the `/GHIDRA_INSTALL_DIR/Extensions/Ghidra` directory is not recognized as an extension to be enabled.

**Comment by hazzaaclark** [comment]
Hi - thank you for the report

While this is still a work in progress, as I have no included the rest of the Assemblies for combating even the most basic of necessities, I can provide some help as and where I can

As I continue to work on this project, here are some helpful pointers you can use in the meantime to ensure a proper build process:

1. Check Ghidra and JDK installations:

Verify that Ghidra and JDK are properly installed on your system.
You can check the installation of JDK by opening a terminal and typing java -version.
For Ghidra, navigate to the directory where it’s installed and ensure you can run it without issues.


2. Verify the ‘ghidraInstallDir’ property:

This property should be defined in your gradle.properties file and point to the directory where Ghidra is installed.
If the property is not defined, you can define it as follows: ghidraInstallDir=/path/to/ghidra
Replace /path/to/ghidra with the actual path to your Ghidra installation.

**Comment by biggestsonicfan** [comment]
I see at this point `ghidraInstallDir` has been removed entirely, which makes sense as it was defined elsewhere in the environment. Ghidra and JDK were installed properly at the time of filing this issue, so I will create a new issue now that we can move forward.
